[
    {
      "name": "The Girl with the Dragon Tattoo",
      "ISBN": "978-0-307-27525-3",
      "author": "Stieg Larsson",
      "category": "Mystery",
      "description": "The Girl with the Dragon Tattoo is a mystery novel by Stieg Larsson. Journalist Mikael Blomkvist is aided in his search for a woman who has been missing for forty years by Lisbeth Salander, a young computer hacker.",
      "img": "https://example.com/book-cover6.jpg",
      "language": "English",
      "pages": 672,
      "publishedYear": "2005",
      "publisher": "Norstedts Förlag",
      "qty": 7,
      "rating": 4.4
    },
    {
      "name": "Gone Girl",
      "ISBN": "978-0-307-58836-4",
      "author": "Gillian Flynn",
      "category": "Mystery",
      "description": "Gone Girl, written by Gillian Flynn, is a mystery thriller novel that delves into the complexities of a troubled marriage. When Amy Dunne disappears on her fifth wedding anniversary, suspicion turns to her husband Nick, unraveling a twisted tale of secrets and deceit.",
      "img": "https://example.com/book-cover7.jpg",
      "language": "English",
      "pages": 419,
      "publishedYear": "2012",
      "publisher": "Crown Publishing Group",
      "qty": 8,
      "rating": 4.1
    },
    {
      "name": "The Da Vinci Code",
      "ISBN": "978-0-385-50420-5",
      "author": "Dan Brown",
      "category": "Mystery",
      "description": "The Da Vinci Code by Dan Brown is a mystery thriller that follows symbologist Robert Langdon and cryptologist Sophie Neveu as they uncover clues hidden in famous works of art. Racing through Europe, they unravel a centuries-old mystery that could shake the foundations of Christianity.",
      "img": "https://example.com/book-cover8.jpg",
      "language": "English",
      "pages": 454,
      "publishedYear": "2003",
      "publisher": "Doubleday",
      "qty": 6,
      "rating": 4.0
    },
    {
      "name": "Big Little Lies",
      "ISBN": "978-0-399-59328-7",
      "author": "Liane Moriarty",
      "category": "Mystery",
      "description": "Big Little Lies, written by Liane Moriarty, is a mystery drama novel that explores the lives of three women, each with their own secrets. Their lives intertwine leading to a shocking event at a school trivia night, exposing the complexities of friendship, marriage, and deception.",
      "img": "https://example.com/book-cover9.jpg",
      "language": "English",
      "pages": 460,
      "publishedYear": "2014",
      "publisher": "Penguin Publishing Group",
      "qty": 9,
      "rating": 4.3
    },
    {
      "name": "The Silent Patient",
      "ISBN": "978-1-250-30169-7",
      "author": "Alex Michaelides",
      "category": "Mystery",
      "description": "The Silent Patient by Alex Michaelides is a psychological mystery thriller. Alicia Berenson, a famous painter, shoots her husband and then stops speaking. Theo Faber, a psychotherapist, is determined to uncover the truth behind her silence and unravel the mystery of that fateful night.",
      "img": "https://example.com/book-cover10.jpg",
      "language": "English",
      "pages": 336,
      "publishedYear": "2019",
      "publisher": "Celadon Books",
      "qty": 5,
      "rating": 4.6
    }
  ,
    {
      "name": "Harry Potter and the Sorcerer's Stone",
      "ISBN": "978-3-16-148410-0",
      "author": "J.K. Rowling",
      "category": "Fantasy",
      "description": "Harry Potter and the Sorcerer's Stone follows the story of a young wizard, Harry Potter, as he discovers his magical heritage and attends Hogwarts School of Witchcraft and Wizardry. Alongside his friends Ron and Hermione, Harry uncovers mysteries and battles dark forces.",
      "img": "https://example.com/book-cover.jpg",
      "language": "English",
      "pages": 320,
      "publishedYear": "1997",
      "publisher": "Bloomsbury Publishing",
      "qty": 10,
      "rating": 4.5
    },
    {
      "name": "The Name of the Wind",
      "ISBN": "978-0-7528-9050-3",
      "author": "Patrick Rothfuss",
      "category": "Fantasy",
      "description": "The Name of the Wind is the story of Kvothe, an adventurer and musician known for his magical abilities. He recounts his life's tale, including his time at the University, his encounters with magic and intrigue, and his pursuit of knowledge and revenge.",
      "img": "https://example.com/book-cover2.jpg",
      "language": "English",
      "pages": 662,
      "publishedYear": "2007",
      "publisher": "DAW Books",
      "qty": 8,
      "rating": 4.7
    },
    {
      "name": "Mistborn: The Final Empire",
      "ISBN": "978-0-7653-5615-5",
      "author": "Brandon Sanderson",
      "category": "Fantasy",
      "description": "Mistborn: The Final Empire is set in a world ruled by the immortal Lord Ruler. It follows Vin, a street urchin with mysterious powers, as she joins a crew planning to overthrow the Lord Ruler's tyrannical reign using unique and powerful abilities.",
      "img": "https://example.com/book-cover3.jpg",
      "language": "English",
      "pages": 541,
      "publishedYear": "2006",
      "publisher": "Tor Books",
      "qty": 6,
      "rating": 4.6
    },
    {
      "name": "The Hobbit",
      "ISBN": "978-0-618-00221-4",
      "author": "J.R.R. Tolkien",
      "category": "Fantasy",
      "description": "The Hobbit is an adventure novel by J.R.R. Tolkien, following Bilbo Baggins on a quest to reclaim the dwarves' homeland from the fearsome dragon Smaug. Along the way, Bilbo encounters trolls, elves, goblins, and a mysterious ring.",
      "img": "https://example.com/book-cover4.jpg",
      "language": "English",
      "pages": 310,
      "publishedYear": "1937",
      "publisher": "George Allen & Unwin",
      "qty": 10,
      "rating": 4.8
    },
    {
      "name": "A Game of Thrones",
      "ISBN": "978-0-553-57340-4",
      "author": "George R.R. Martin",
      "category": "Fantasy",
      "description": "A Game of Thrones is the first book in the epic series 'A Song of Ice and Fire.' It introduces the Seven Kingdoms of Westeros, following the power struggles, alliances, and conflicts among noble families vying for control of the Iron Throne.",
      "img": "https://example.com/book-cover5.jpg",
      "language": "English",
      "pages": 694,
      "publishedYear": "1996",
      "publisher": "Bantam Spectra",
      "qty": 9,
      "rating": 4.4
    }
  ,
    {
      "name": "Dune",
      "ISBN": "978-0-441-17271-9",
      "author": "Frank Herbert",
      "category": "Sci-Fi",
      "description": "Dune is a science fiction novel set in a distant future amidst a feudal interstellar society. It follows Paul Atreides as he navigates political intrigue, religion, and the desert planet Arrakis, the only source of the most valuable substance in the universe.",
      "img": "https://example.com/book-cover11.jpg",
      "language": "English",
      "pages": 694,
      "publishedYear": "1965",
      "publisher": "Chilton Books",
      "qty": 7,
      "rating": 4.6
    },
    {
      "name": "Neuromancer",
      "ISBN": "978-0-441-17271-9",
      "author": "William Gibson",
      "category": "Sci-Fi",
      "description": "Neuromancer is a seminal cyberpunk novel that follows the story of Case, a washed-up computer hacker, hired for one last job in a world dominated by powerful artificial intelligence. The narrative explores themes of artificial reality and the manipulation of information.",
      "img": "https://example.com/book-cover12.jpg",
      "language": "English",
      "pages": 271,
      "publishedYear": "1984",
      "publisher": "Ace Books",
      "qty": 6,
      "rating": 4.3
    },
    {
      "name": "Foundation",
      "ISBN": "978-0-553-29335-7",
      "author": "Isaac Asimov",
      "category": "Sci-Fi",
      "description": "Foundation is a science fiction novel that revolves around the decline and fall of the Galactic Empire. Mathematician Hari Seldon develops 'psychohistory' to predict the future and minimize the ensuing dark age after the empire's collapse.",
      "img": "https://example.com/book-cover13.jpg",
      "language": "English",
      "pages": 244,
      "publishedYear": "1951",
      "publisher": "Gnome Press",
      "qty": 8,
      "rating": 4.5
    },
    {
      "name": "Snow Crash",
      "ISBN": "978-0-553-08853-2",
      "author": "Neal Stephenson",
      "category": "Sci-Fi",
      "description": "Snow Crash is a dystopian cyberpunk novel set in a near-future America. It follows Hiro Protagonist, a hacker and pizza delivery driver, as he investigates a dangerous computer virus called Snow Crash that affects both the virtual and physical worlds.",
      "img": "https://example.com/book-cover14.jpg",
      "language": "English",
      "pages": 470,
      "publishedYear": "1992",
      "publisher": "Bantam Books",
      "qty": 5,
      "rating": 4.2
    },
    {
      "name": "The Martian",
      "ISBN": "978-0-8041-3902-1",
      "author": "Andy Weir",
      "category": "Sci-Fi",
      "description": "The Martian is a science fiction novel that follows astronaut Mark Watney, stranded alone on Mars after a mission gone wrong. It chronicles his struggle for survival and his resourcefulness in trying to find a way to communicate with Earth.",
      "img": "https://example.com/book-cover15.jpg",
      "language": "English",
      "pages": 369,
      "publishedYear": "2011",
      "publisher": "Crown Publishing Group",
      "qty": 9,
      "rating": 4.7
    }
  ,
    {
      "name": "Watchmen",
      "ISBN": "978-0-930289-23-4",
      "author": "Alan Moore",
      "category": "Comic",
      "description": "Watchmen is a graphic novel that presents an alternate history where superheroes emerged in the 1940s. The story delves into complex themes, including power, morality, and the consequences of playing hero in a gritty and realistic world.",
      "img": "https://example.com/book-cover16.jpg",
      "language": "English",
      "pages": 416,
      "publishedYear": "1987",
      "publisher": "DC Comics",
      "qty": 7,
      "rating": 4.8
    },
    {
      "name": "Maus",
      "ISBN": "978-0-399-15047-9",
      "author": "Art Spiegelman",
      "category": "Comic",
      "description": "Maus is a graphic memoir that recounts the experiences of the author's father, a Holocaust survivor, depicted as anthropomorphic animals. The narrative powerfully explores the impact of trauma and the legacy of survival.",
      "img": "https://example.com/book-cover17.jpg",
      "language": "English",
      "pages": 296,
      "publishedYear": "1986",
      "publisher": "Pantheon Books",
      "qty": 6,
      "rating": 4.7
    },
    {
      "name": "Sandman",
      "ISBN": "978-1-56389-011-6",
      "author": "Neil Gaiman",
      "category": "Comic",
      "description": "Sandman is a comic series that follows Dream, one of the Endless, as he navigates various realms and encounters mythical beings. The series weaves together dark fantasy, horror, and mythology in a compelling narrative.",
      "img": "https://example.com/book-cover18.jpg",
      "language": "English",
      "pages": 240,
      "publishedYear": "1989",
      "publisher": "DC Comics",
      "qty": 8,
      "rating": 4.6
    },
    {
      "name": "Saga",
      "ISBN": "978-1-60706-601-9",
      "author": "Brian K. Vaughan",
      "category": "Comic",
      "description": "Saga is a space opera comic series that follows two lovers from warring extraterrestrial races as they fight to protect their newborn daughter. The story explores themes of love, war, and family against a vast intergalactic backdrop.",
      "img": "https://example.com/book-cover19.jpg",
      "language": "English",
      "pages": 160,
      "publishedYear": "2012",
      "publisher": "Image Comics",
      "qty": 5,
      "rating": 4.9
    },
    {
      "name": "Batman: The Dark Knight Returns",
      "ISBN": "978-0-930289-27-2",
      "author": "Frank Miller",
      "category": "Comic",
      "description": "Batman: The Dark Knight Returns is a graphic novel that portrays an older Bruce Wayne returning to crime-fighting after a long retirement. The story explores a darker, more mature take on the Batman mythos.",
      "img": "https://example.com/book-cover20.jpg",
      "language": "English",
      "pages": 224,
      "publishedYear": "1986",
      "publisher": "DC Comics",
      "qty": 9,
      "rating": 4.5
    }
  ,
    {
      "name": "Pride and Prejudice",
      "ISBN": "978-0-14-143951-8",
      "author": "Jane Austen",
      "category": "Romance",
      "description": "Pride and Prejudice follows the story of Elizabeth Bennet and Mr. Darcy, exploring themes of love, class, and societal expectations in 19th-century England. The novel is a timeless classic that delves into the complexities of relationships.",
      "img": "https://example.com/book-cover21.jpg",
      "language": "English",
      "pages": 432,
      "publishedYear": "1813",
      "publisher": "Penguin Classics",
      "qty": 7,
      "rating": 4.7
    },
    {
      "name": "Outlander",
      "ISBN": "978-0-440-24387-1",
      "author": "Diana Gabaldon",
      "category": "Romance",
      "description": "Outlander is a time-travel romance novel following Claire Randall, a World War II nurse who finds herself transported back in time to 18th-century Scotland. Amidst political intrigue and danger, she falls in love with a Highland warrior.",
      "img": "https://example.com/book-cover22.jpg",
      "language": "English",
      "pages": 850,
      "publishedYear": "1991",
      "publisher": "Dell Publishing",
      "qty": 6,
      "rating": 4.5
    },
    {
      "name": "Me Before You",
      "ISBN": "978-0-14-312454-2",
      "author": "Jojo Moyes",
      "category": "Romance",
      "description": "Me Before You is a contemporary romance novel that tells the story of Louisa Clark, a young woman who becomes a caregiver for Will Traynor, a paralyzed man. Their evolving relationship challenges both of them to reconsider what it means to live fully.",
      "img": "https://example.com/book-cover23.jpg",
      "language": "English",
      "pages": 400,
      "publishedYear": "2012",
      "publisher": "Penguin Books",
      "qty": 8,
      "rating": 4.6
    },
    {
      "name": "The Notebook",
      "ISBN": "978-0-446-52080-5",
      "author": "Nicholas Sparks",
      "category": "Romance",
      "description": "The Notebook is a heartfelt love story between Noah Calhoun and Allie Nelson, spanning decades and reflecting on the enduring power of love and memory. It explores the challenges and beauty of long-lasting relationships.",
      "img": "https://example.com/book-cover24.jpg",
      "language": "English",
      "pages": 213,
      "publishedYear": "1996",
      "publisher": "Warner Books",
      "qty": 9,
      "rating": 4.4
    },
    {
      "name": "The Time Traveler's Wife",
      "ISBN": "978-0-15-602943-8",
      "author": "Audrey Niffenegger",
      "category": "Romance",
      "description": "The Time Traveler's Wife is a unique love story that chronicles the life of Clare and Henry, a couple challenged by Henry's involuntary time-traveling. Their relationship navigates the complexities of time and its impact on their lives.",
      "img": "https://example.com/book-cover25.jpg",
      "language": "English",
      "pages": 546,
      "publishedYear": "2003",
      "publisher": "Harvest Books",
      "qty": 10,
      "rating": 4.8
    }
  ,
    {
      "name": "Into the Wild",
      "ISBN": "978-0-385-51837-2",
      "author": "Jon Krakauer",
      "category": "Travel",
      "description": "Into the Wild follows the true story of Christopher McCandless, a young man who left behind his possessions and set off into the Alaskan wilderness, seeking adventure and a connection with nature. The book explores themes of self-discovery and the allure of the unknown.",
      "img": "https://example.com/book-cover26.jpg",
      "language": "English",
      "pages": 240,
      "publishedYear": "1996",
      "publisher": "Anchor Books",
      "qty": 7,
      "rating": 4.5
    },
    {
      "name": "Eat, Pray, Love",
      "ISBN": "978-0-14-303841-2",
      "author": "Elizabeth Gilbert",
      "category": "Travel",
      "description": "Eat, Pray, Love is a memoir detailing the author's journey across Italy, India, and Indonesia after a difficult divorce. Through food, spirituality, and love, she explores different cultures and seeks to rediscover herself.",
      "img": "https://example.com/book-cover27.jpg",
      "language": "English",
      "pages": 368,
      "publishedYear": "2006",
      "publisher": "Penguin Books",
      "qty": 6,
      "rating": 4.4
    },
    {
      "name": "A Walk in the Woods",
      "ISBN": "978-0-7679-0252-6",
      "author": "Bill Bryson",
      "category": "Travel",
      "description": "A Walk in the Woods chronicles the author's attempt to hike the Appalachian Trail, a journey filled with humor, encounters with wildlife, and reflections on nature and personal challenges. Bryson's engaging narrative offers insight into the trail and its history.",
      "img": "https://example.com/book-cover28.jpg",
      "language": "English",
      "pages": 276,
      "publishedYear": "1998",
      "publisher": "Broadway Books",
      "qty": 8,
      "rating": 4.6
    },
    {
      "name": "The Alchemist",
      "ISBN": "978-0-06-112241-5",
      "author": "Paulo Coelho",
      "category": "Travel",
      "description": "The Alchemist is a philosophical novel following Santiago, a shepherd boy, as he embarks on a journey to fulfill his dreams. The story explores themes of destiny, personal legends, and the pursuit of one's purpose in life.",
      "img": "https://example.com/book-cover29.jpg",
      "language": "English",
      "pages": 197,
      "publishedYear": "1988",
      "publisher": "HarperOne",
      "qty": 9,
      "rating": 4.3
    },
    {
      "name": "Wild",
      "ISBN": "978-0-307-59273-6",
      "author": "Cheryl Strayed",
      "category": "Travel",
      "description": "Wild is a memoir recounting the author's solo journey along the Pacific Crest Trail after personal turmoil. Strayed's hike becomes a transformative experience, revealing the healing power of nature and the strength found in self-discovery.",
      "img": "https://example.com/book-cover30.jpg",
      "language": "English",
      "pages": 315,
      "publishedYear": "2012",
      "publisher": "Knopf",
      "qty": 10,
      "rating": 4.7
    },  
    {
      "name": "Sapiens: A Brief History of Humankind",
      "ISBN": "978-0-06-231609-7",
      "author": "Yuval Noah Harari",
      "category": "History",
      "description": "Sapiens provides a sweeping overview of human history, from the emergence of Homo sapiens in Africa to the present day. The book explores how cultural, social, and cognitive revolutions shaped the course of human development.",
      "img": "https://example.com/book-cover31.jpg",
      "language": "English",
      "pages": 443,
      "publishedYear": "2014",
      "publisher": "Harper",
      "qty": 7,
      "rating": 4.6
    },
    {
      "name": "A People's History of the United States",
      "ISBN": "978-0-06-083865-2",
      "author": "Howard Zinn",
      "category": "History",
      "description": "A People's History of the United States presents a perspective on American history from the viewpoint of marginalized groups, highlighting the struggles of Native Americans, African Americans, women, and laborers throughout the country's history.",
      "img": "https://example.com/book-cover32.jpg",
      "language": "English",
      "pages": 729,
      "publishedYear": "1980",
      "publisher": "Harper Perennial",
      "qty": 6,
      "rating": 4.5
    },
    {
      "name": "The Guns of August",
      "ISBN": "978-0-345-38623-4",
      "author": "Barbara W. Tuchman",
      "category": "History",
      "description": "The Guns of August is a detailed account of the first month of World War I, exploring the political, military, and social factors that led to the conflict and its devastating consequences. Tuchman's narrative focuses on the events leading up to the war's outbreak.",
      "img": "https://example.com/book-cover33.jpg",
      "language": "English",
      "pages": 511,
      "publishedYear": "1962",
      "publisher": "Presidio Press",
      "qty": 8,
      "rating": 4.7
    },
    {
      "name": "1491: New Revelations of the Americas Before Columbus",
      "ISBN": "978-1-4000-3205-1",
      "author": "Charles C. Mann",
      "category": "History",
      "description": "1491 explores the Americas before the arrival of Christopher Columbus, challenging traditional notions about indigenous cultures. The book presents a rich and complex picture of pre-Columbian civilizations and their impact on the continent.",
      "img": "https://example.com/book-cover34.jpg",
      "language": "English",
      "pages": 541,
      "publishedYear": "2005",
      "publisher": "Knopf",
      "qty": 9,
      "rating": 4.4
    },
    {
      "name": "The Silk Roads: A New History of the World",
      "ISBN": "978-1-4088-3999-7",
      "author": "Peter Frankopan",
      "category": "History",
      "description": "The Silk Roads traces the history of civilization by examining the impact of trade, culture, and ideas along the ancient Silk Road routes. Frankopan's narrative explores the interconnectedness of different cultures and societies.",
      "img": "https://example.com/book-cover35.jpg",
      "language": "English",
      "pages": 645,
      "publishedYear": "2015",
      "publisher": "Bloomsbury",
      "qty": 10,
      "rating": 4.8
    }
  ]
            