[
    {
        "name": "The Great Gatsby",
        "author": "F. Scott Fitzgerald",
        "img": "https://example.com/great_gatsby.jpg",
        "qty": 5,
        "category": "Classic Literature",
        "rating": 4.2,
        "description": "A story of the extravagance and excesses of the Jazz Age. Set in the 1920s, it follows the enigmatic Jay Gatsby and his pursuit of Daisy Buchanan amidst the backdrop of wealth, parties, and societal changes.",
        "ISBN": "978-0743273565",
        "publisher": "Scribner",
        "published_date": "April 10, 1925",
        "pages": 180,
        "language": "English"
    },
    {
        "name": "To Kill a Mockingbird",
        "author": "Harper Lee",
        "img": "https://example.com/to_kill_a_mockingbird.jpg",
        "qty": 7,
        "category": "Fiction",
        "rating": 4.5,
        "description": "A powerful exploration of racial injustice and moral growth in a small Southern town. Through the eyes of young Scout Finch, it addresses themes of compassion, integrity, and the loss of innocence.",
        "ISBN": "978-0061120084",
        "publisher": "J. B. Lippincott & Co.",
        "published_date": "July 11, 1960",
        "pages": 336,
        "language": "English"
    },
    {
        "name": "The Catcher in the Rye",
        "author": "J.D. Salinger",
        "img": "https://example.com/catcher_in_the_rye.jpg",
        "qty": 3,
        "category": "Coming of Age",
        "rating": 4.0,
        "description": "Follows the journey of a disenchanted teenager through New York City, exploring themes of teenage angst, alienation, and the search for authenticity.",
        "ISBN": "978-0316769488",
        "publisher": "Little, Brown and Company",
        "published_date": "July 16, 1951",
        "pages": 224,
        "language": "English"
    },
    {
        "name": "1984",
        "author": "George Orwell",
        "img": "https://example.com/1984.jpg",
        "qty": 6,
        "category": "Dystopian",
        "rating": 4.7,
        "description": "A classic portrayal of a totalitarian society and individual resistance, focusing on the consequences of government overreach, surveillance, and manipulation.",
        "ISBN": "978-0451524935",
        "publisher": "Secker & Warburg",
        "published_date": "June 8, 1949",
        "pages": 328,
        "language": "English"
    },
    {
        "name": "Pride and Prejudice",
        "author": "Jane Austen",
        "img": "https://example.com/pride_and_prejudice.jpg",
        "qty": 4,
        "category": "Romantic Fiction",
        "rating": 4.6,
        "description": "A witty commentary on society and love in the 19th century, focusing on Elizabeth Bennet's journey of self-discovery and her relationship with the enigmatic Mr. Darcy.",
        "ISBN": "978-0141439518",
        "publisher": "T. Egerton, Whitehall",
        "published_date": "January 28, 1813",
        "pages": 432,
        "language": "English"
    },
    {
        "name": "The Hobbit",
        "author": "J.R.R. Tolkien",
        "img": "https://example.com/the_hobbit.jpg",
        "qty": 8,
        "category": "Fantasy",
        "rating": 4.8,
        "description": "A captivating adventure in a magical world, following Bilbo Baggins' journey with a group of dwarves to reclaim their homeland from the dragon Smaug.",
        "ISBN": "978-0547928227",
        "publisher": "George Allen & Unwin",
        "published_date": "September 21, 1937",
        "pages": 310,
        "language": "English"
    },
    {
        "name": "The Alchemist",
        "author": "Paulo Coelho",
        "img": "https://example.com/the_alchemist.jpg",
        "qty": 10,
        "category": "Philosophical Fiction",
        "rating": 4.4,
        "description": "Follows the journey of a shepherd named Santiago as he seeks his personal legend, encountering spiritual teachings and life lessons along the way.",
        "ISBN": "978-0062315007",
        "publisher": "HarperCollins",
        "published_date": "1988",
        "pages": 208,
        "language": "English"
    },
    {
        "name": "The Road",
        "author": "Cormac McCarthy",
        "img": "https://example.com/the_road.jpg",
        "qty": 2,
        "category": "Post-Apocalyptic",
        "rating": 4.3,
        "description": "A father and son's journey in a bleak, post-apocalyptic world, navigating through dangers while holding onto their humanity.",
        "ISBN": "978-0307387899",
        "publisher": "Alfred A. Knopf",
        "published_date": "September 26, 2006",
        "pages": 287,
        "language": "English"
    },
    {
        "name": "The Art of War",
        "author": "Sun Tzu",
        "img": "https://example.com/the_art_of_war.jpg",
        "qty": 9,
        "category": "Military Strategy",
        "rating": 4.9,
        "description": "An ancient Chinese treatise on warfare and strategy, emphasizing the importance of planning, deception, and understanding the enemy.",
        "ISBN": "978-1590302255",
        "publisher": "Sunzi Bingfa Publishing",
        "published_date": "5th century BC",
        "pages": 273,
        "language": "Chinese"
    },
    {
        "name": "Sapiens: A Brief History of Humankind",
        "author": "Yuval Noah Harari",
        "img": "https://example.com/sapiens.jpg",
        "qty": 6,
        "category": "History",
        "rating": 4.7,
        "description": "Explores the history of humankind from ancient times to the present, discussing cognitive, agricultural, and scientific revolutions that shaped human societies.",
        "ISBN": "978-0062316097",
        "publisher": "Harper",
        "published_date": "February 10, 2015",
        "pages": 443,
        "language": "English"
    },
    {
        "name": "The Lord of the Rings",
        "author": "J.R.R. Tolkien",
        "img": "https://example.com/lord_of_the_rings.jpg",
        "qty": 4,
        "category": "Fantasy",
        "rating": 4.9,
        "description": "An epic fantasy trilogy following the quest to destroy the One Ring, featuring memorable characters, battles, and a richly detailed world.",
        "ISBN": "978-0261103252",
        "publisher": "George Allen & Unwin",
        "published_date": "July 29, 1954",
        "pages": 1178,
        "language": "English"
    },
    {
        "name": "The Chronicles of Narnia",
        "author": "C.S. Lewis",
        "img": "https://example.com/chronicles_of_narnia.jpg",
        "qty": 6,
        "category": "Fantasy",
        "rating": 4.6,
        "description": "A series of seven high-fantasy novels exploring the adventures in the magical land of Narnia, where animals talk and epic battles between good and evil unfold.",
        "ISBN": "978-0066238500",
        "publisher": "Geoffrey Bles",
        "published_date": "1950-1956",
        "pages": 767,
        "language": "English"
    },
    {
        "name": "The Da Vinci Code",
        "author": "Dan Brown",
        "img": "https://example.com/da_vinci_code.jpg",
        "qty": 8,
        "category": "Mystery Thriller",
        "rating": 4.3,
        "description": "A gripping thriller revolving around symbologist Robert Langdon's quest to solve a murder mystery with hidden religious symbolism.",
        "ISBN": "978-0307474278",
        "publisher": "Doubleday",
        "published_date": "March 18, 2003",
        "pages": 597,
        "language": "English"
    },
    {
        "name": "Harry Potter and the Sorcerer's Stone",
        "author": "J.K. Rowling",
        "img": "https://example.com/harry_potter_sorcerers_stone.jpg",
        "qty": 10,
        "category": "Fantasy",
        "rating": 4.8,
        "description": "Introduces the wizarding world and the journey of a young wizard, Harry Potter, as he discovers his magical heritage and battles dark forces.",
        "ISBN": "978-0590353427",
        "publisher": "Bloomsbury",
        "published_date": "June 26, 1997",
        "pages": 309,
        "language": "English"
    },
    {
        "name": "The Hunger Games",
        "author": "Suzanne Collins",
        "img": "https://example.com/hunger_games.jpg",
        "qty": 5,
        "category": "Young Adult",
        "rating": 4.4,
        "description": "Set in a dystopian world, it follows Katniss Everdeen's journey in a deadly televised competition, challenging societal norms and authority.",
        "ISBN": "978-0439023481",
        "publisher": "Scholastic Press",
        "published_date": "September 14, 2008",
        "pages": 374,
        "language": "English"
    },
    {
        "name": "The Kite Runner",
        "author": "Khaled Hosseini",
        "img": "https://example.com/kite_runner.jpg",
        "qty": 7,
        "category": "Contemporary Fiction",
        "rating": 4.7,
        "description": "Explores the complexities of friendship, betrayal, and redemption in war-torn Afghanistan through the lives of Amir and Hassan.",
        "ISBN": "978-1594480003",
        "publisher": "Riverhead Books",
        "published_date": "May 29, 2003",
        "pages": 371,
        "language": "English"
    },
    {
        "name": "The Girl on the Train",
        "author": "Paula Hawkins",
        "img": "https://example.com/girl_on_the_train.jpg",
        "qty": 3,
        "category": "Mystery Thriller",
        "rating": 4.2,
        "description": "A psychological thriller narrated by three women, entangled in a gripping story of obsession, deceit, and suspense.",
        "ISBN": "978-1594634024",
        "publisher": "Riverhead Books",
        "published_date": "January 13, 2015",
        "pages": 336,
        "language": "English"
    },
    {
        "name": "The Fault in Our Stars",
        "author": "John Green",
        "img": "https://example.com/fault_in_our_stars.jpg",
        "qty": 4,
        "category": "Young Adult",
        "rating": 4.5,
        "description": "A heartrending story of young cancer patients Hazel and Gus, exploring love, loss, and the pursuit of meaning in life.",
        "ISBN": "978-0525478812",
        "publisher": "Dutton Books",
        "published_date": "January 10, 2012",
        "pages": 313,
        "language": "English"
    },
    {
        "name": "Gone Girl",
        "author": "Gillian Flynn",
        "img": "https://example.com/gone_girl.jpg",
        "qty": 6,
        "category": "Mystery Thriller",
        "rating": 4.3,
        "description": "A psychological thriller centered around the mysterious disappearance of Amy Dunne and the suspicions surrounding her husband, Nick.",
        "ISBN": "978-0307588371",
        "publisher": "Crown Publishing Group",
        "published_date": "June 5, 2012",
        "pages": 419,
        "language": "English"
    },
    {
        "name": "Educated",
        "author": "Tara Westover",
        "img": "https://example.com/educated.jpg",
        "qty": 5,
        "category": "Memoir",
        "rating": 4.7,
        "description": "A memoir detailing Tara Westover's journey from an isolated upbringing in a strict household to her pursuit of education and self-discovery.",
        "ISBN": "978-0399590504",
        "publisher": "Random House",
        "published_date": "February 20, 2018",
        "pages": 352,
        "language": "English"
    }
]
